language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libeigen3-dev
            - cmake
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libeigen3-dev
            - cmake
    - os: osx
      # TODO
  allow_failures:
    - os: osx

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir build && cd build && cmake .. && make -j && ./kalman_test ; fi
